### ISSUE TITLE
Storage put into FeatureManager service

### ISSUE THREAD

**Issue by jakubderdziak** [novaway/NovawayFeatureFlagBundle#38]
I'm not sure if it is a bug, but can you explain me this:

According to documentation to set my own storage I should implement StorageInterface and register it:

```
novaway_feature_flag:
    storage: your.custom.service.name

```
Now I can call it as a service:
```
        $featureManager = $this->get('novaway_feature_flag.manager.feature');

        if ($featureManager->isEnabled('my_feature_1')) {
            // my_feature_1 is enabled
        }
```

But as I can see, service `novaway_feature_flag.manager.feature` is configured from storage config:
```
        $container->setAlias('novaway_feature_flag.storage', $config['storage']);

        $container
            ->setAlias('novaway_feature_flag.manager.feature', $config['storage'])
```
so what I have here is exactly my implementation on StorageInterface. Although methods isEnabled and isDisabled are deprecated in StorageInterface and I should not use them. So what is correct way to use it, so I won't be force to use deprecated methods. 

Should not implementation of interface FeatureManager be used as `novaway_feature_flag.storage` alias?

**Comment by jdecool** [comment]
Hi @jakubderdziak,

It takes time but we're currently working on [a new version of the bundle](https://github.com/novaway/NovawayFeatureFlagBundle/issues/32).

With this new version, we're going to fix some design constraints. Currently the `Storage` through the `StorageInterface` has too many responsibilities. It has to describe how your features need to be stored and accessed. But it's also responsible to check if the feature is enabled or not.

So when you want to create a new storage you should reimplement the feature enabled checks.

To solved this problem, the `StorageInterface` has been split into `Storage` & `FeatureManager`.

The first one manages the feature storage and the check if the feature is enabled. So you don't need to reimplement this logic for each storage.

To allow a smooth transition between the V2 and V3, we start to introduce the `FeatureManager` service without change anything to the current bundle configuration.
That's why the current configuration is defined as you described it.

In the next version, you have to work only with `novaway_feature_flag.manager` and `novaway_feature_flag.storage` and `novaway_feature_flag.manager.feature` won't be exposed to your project anymore (it will be only internal bundle).

**Comment by jakubderdziak** [comment]
Thank you for your response. Hopefully V3 will release soon enough.

**Comment by jdecool** [comment]
Hey, we've just release the [`3.0.0-alpha1`](https://github.com/novaway/NovawayFeatureFlagBundle/releases/tag/3.0.0-alpha1)

Feel free to test it and give feedback.
